version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: /bin/bash -c ". /app/venv/bin/activate && python app.py"
