version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app.py
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 6g
